suites:
  # - name: git-default
  #   run_list: ["recipe[git]"]
  #   includes: [ubuntu-14.04]
  # - name: git-source
  #   run_list: ["recipe[git::source]"]
  #   includes: [nonexistent]
  # - name: git-default-windows
  #   run_list: ["recipe[git]"]
  #   includes: [windows-2012r2]
  - name: learn-the-basics-rhel
    includes: [el-6]
